name: Check code

on:
  push:
    branches: ["main"]

  # Allows workflow to manuallly be run from the Actions tab
  workflow_dispatch:

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Enable Corepack
        run: corepack enable

      - name: Use correct Yarn version
        run: corepack prepare --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check code
        run: yarn check-code
